---
- name: Create Snapshot
  hosts: all
  become: yes 

  tasks:
    - name: Download and Extracting AWS CLI script
      unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/home/ubuntu"
        remote_src: yes
    
    - name: Running AWS CLI Script 
      shell: ./aws/install
      args:
        chdir: "/home/ubuntu"
    
    - name: Configure AWS CLI
      environment: 
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    
    - name: Create Snapshot directory
      file:
        path: /home/ubuntu/zeeve/avax_snapshot
        state: directory
    
    - name: Get Today's Date
      set_fact:
        today_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Copy compare script
      copy:
        src: compare_latest_block.sh
        dest: /home/ubuntu 
        mode: 0777
    
    - name: Execute the Script 
      command: bash /home/ubuntu/compare_latest_block.sh {{ network }}
    
    - name: Create Tarfile with Dynamic Name
      command: tar czf /home/ubuntu/zeeve/avax_snapshot/avalanche-test-{{ network }}-snap-{{ today_date }}.tar.gz -C /home/ubuntu/zeeve/avalanchego/ .

    - name: Upload snapshot to bucket 
      command: aws --endpoint-url https://ams1.vultrobjects.com s3 cp /home/ubuntu/zeeve/avax_snapshot/avalanche-test-{{ network }}-snap-{{ today_date }}.tar.gz s3://avax-snapshots-zeeve-internal/
    
    - name: Make Snapshot Public 
      command: aws --endpoint-url https://ams1.vultrobjects.com s3api put-object-acl --bucket avax-snapshots-zeeve-internal --key avax_snapshot/avalanche-test-{{ network }}-snap-{{ today_date }}.tar.gz --acl public-read
    
    